[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-interaction --no-root
commands =
    poetry run pytest -n auto {posargs:tests}

[testenv:coverage]
commands =
    poetry run pytest -n auto --cov=geo_adjacency --cov-report=term-missing {posargs:tests}
