name: documentation

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Autodoc
        run: |
          sphinx-apidoc -o docs geo_adjacency
      - name: Sphinx build
        run: |
          sphinx-build docs docs/_build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.SPHINX_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
